# Generated by Django 6.0.3 on 2026-08-18 21:15

import apps.descriptive_grading.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('access_code', models.CharField(help_text='4-digit code students use to find and answer this exam', max_length=4, unique=True)),
                ('valid_until', models.DateTimeField(default=apps.descriptive_grading.models.default_valid_until)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('total_marks', models.PositiveIntegerField()),
                ('rubric', models.TextField(help_text='e.g. "5 key points, 2 marks each, total 10"')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='descriptive_grading.exam')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('flagged', 'Flagged')], default='pending', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='descriptive_grading.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='DescriptiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_raw_text', models.TextField(blank=True, null=True)),
                ('ocr_cleaned_text', models.TextField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('retrieved_chunks', models.JSONField(blank=True, default=list, null=True)),
                ('marks_awarded', models.FloatField(blank=True, null=True)),
                ('total_marks', models.FloatField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('justification', models.JSONField(blank=True, default=dict, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='descriptive_grading.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='descriptive_grading.submission')),
            ],
            options={
                'db_table': 'descriptive_results',
            },
        ),
        migrations.CreateModel(
            name='TeacherMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='teacher_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chunked', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_materials',
            },
        ),
    ]
