# Generated by Django 6.0.2 on 2026-08-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptive_grading', '0002_add_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiveresult',
            name='answer_sheet',
            field=models.ImageField(blank=True, help_text='The answer sheet image the student uploaded for this answer.', null=True, upload_to='answer_sheets/'),
        ),
    ]
