# Generated by Django 5.2.17 on 2026-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptive_grading', '0003_descriptiveresult_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiveresult',
            name='ground_truth_marks',
            field=models.FloatField(blank=True, help_text='Independently assigned teacher mark for evaluation purposes (distinct from manual_review overrides, which only exist for flagged/disputed results).', null=True),
        ),
    ]
